version: '3.7'
services:
    db:
        image: 'postgres'
        restart: always
        env_file:
            - ./.env
        ports:
            - '5432:5432'
        volumes:
            - dbdata_prod:/var/lib/postgresql/data
    server:
        build:
            context: './'
            dockerfile: dockerfile
            target: prod

        restart: always
        env_file:
            - ./.env
        volumes:
            - ./:/app
            - /app/node_modules
        command: npm run start
        ports:
            - '3000:3000'
        depends_on:
            - db
volumes:
    dbdata_prod:
